* [32mcontent-points[m
  custom-slippage-bg[m
  dev[m
  dynamic-title[m
  input-types-fix[m
  leaderboard-margin-fix[m
  master[m
  mobile-banner-fix[m
  mobile-tooltips-fix[m
  navbar-mobile[m
  nightly-icon-fix[m
  pagination-fix[m
  points-margin-fixes[m
  points-pager-mobile-fix[m
  pool-filter[m
  pool-separators[m
  pool-swap-demo[m
  show-position-details-fix[m
  token-filter-feeTier[m
