name: deploy master

on:
  push:
    branches: [master]

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REACT_APP_NODE_ENV: 'production'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel@41.6.0
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_ORG_ID }}
          ALIAS_DOMAINS: |
            eclipse.invariant.app
